#!/bin/bash

packages_dir=node_modules
node_root=/opt/node

NODE_VERSION=v0.10.12

startdir=$(pwd)

if [ $(node --version) != $(echo $NODE_VERSION | sed -e s/v//g) ]; then
    echo "Node present or not $NODE_VERSION - installing"
    rm -rf $node_root/*
    cd $node_root
    # use binary packages
    curl -L http://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz | tar -zxf-
    mv node-$NODE_VERSION-linux-x64/* $node_root
    cd $startdir
fi

# Copy code to $HOME.
rsync -aH ./ $HOME/
cd $HOME

# Install the specified dependencies.
# This will re-use already installed dependencies.
# To force the use of the latest version of a package:
# - specify a version specification in package.json;
# - or push with the "--clean" flag to discard the incremental build.
[ -f node-modules-dotcloud.tar.gz] && tar xfz node-modules-dotcloud.tar.gz
[ -f package.json ] && npm install -d -d
# install deps for the github-sync program, too
(cd github-sync && npm install -d -d)
